HW9
iarkov/r_d_cpp_gamedev pull request #4
Opened 2023-11-29 21:13 UTC by iarkov

Homework #9: Strings and Arrays

2023-12-11 09:27 UTC, bohdanpc commented on functionsHW9.h
> +#include <cctype>
no includes in headers unless you really need them here for you functions prototypes

2023-12-11 09:27 UTC, bohdanpc commented on functionsHW9.cpp
> +    }
not output but translation of original array

2023-12-11 09:27 UTC, bohdanpc commented on functionsHW9.cpp
> +bool isPalindrom(const char str[]) {
`Паліндром -  слово, число, набір символів, що однаково читається в обох напрямках: зліва направо і справа наліво`
So, ' ' symbol is valid

2023-12-11 09:27 UTC, bohdanpc commented on functionsHW9.cpp
> +        if (isAlpha && isVowel) {
I wonder what symbols are counted as Vowels but not Alpha's

2023-12-11 09:27 UTC, bohdanpc commented on functionsHW9.cpp
> +    if (strlen(str1) == strlen(str2)) {
if (strlen(str1) != strlen(str2)) 
    return false;

int i = 0;
while (str1[i] != '\0') {
        if (str1[i] != str2[i]) {
            return false;
        }
    }
    return false;

Looks much more neat, doesn't it?

Besides, this function doesn't work after all.

2023-12-13 18:16 UTC, helen-black requested changes

2023-12-13 18:16 UTC, helen-black commented on functionsHW9.cpp
>              break;
int wordLength = strlen(str);

2023-12-13 18:16 UTC, helen-black commented on functionsHW9.cpp
>              break;
you don't need break after return

2023-12-13 18:16 UTC, helen-black commented on functionsHW9.cpp
>          else if (isAlpha && !isVowel) {
you already know that isVowel == false

2023-12-13 18:16 UTC, helen-black commented on functionsHW9.cpp
> +    else {
you don't need else here

2023-12-15 14:05 UTC, merged